### ISSUE TITLE
crash soon after injection

### ISSUE THREAD

**Issue by loganmulligan100** [NotDSF/HttpSpy#2]
after injecting it soon crashes. Im using synapse. It seems like everything loads but then crashes

**Comment by NotDSF** [comment]
I cannot reproduce this issue, can you try deleting `HttpSpy` in your workspace folder and trying again? Are you sure you're using the latest version? (with the updated loadstring?)

If this doesn't work tell me here and I'll look into it more

**Comment by loganmulligan100** [comment]
it seems as if there was no httpspy folder created? could this be part of my problem

**Comment by loganmulligan100** [comment]
it seems as if all is well now I didnt think I changed anything but It works . sorry about that!
