### ISSUE TITLE
maybe a synapse thing?

### ISSUE THREAD

**Issue by loganmulligan100** [NotDSF/HttpSpy#3]
I was enjoying using this but now every time i Use script it opens window but the window loads almost like a cmd prompt and then soon after crashes, this might just be a synapse update fuck up but just wanted to see it anyone else having a problem

**Comment by loganmulligan100** [comment]
I test synapse console just by its self and I dont seem to have the same probelm so IDK why its happening

**Comment by NotDSF** [comment]
Yeah it's synapse, whenever I use rconsole on its own I crash

**Comment by loganmulligan100** [comment]
weird ok sounds good
