### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by bobRE12** [NotDSF/HttpSpy#4]
try using replaceclosure instead of hookfunction

**Comment by NotDSF** [comment]
replaceclosure is just an alias for hookfunction

**Comment by bobRE12** [comment]
idk

**Comment by bobRE12** [comment]
try it out

**Comment by bobRE12** [comment]
> alias for hookfunction

https://prnt.sc/awOeoDawnOvt

**Comment by NotDSF** [comment]
Switching to replaceclosure makes no difference at all.

Patching some of the detections are kinda hard due to how syn request works internally, but of course I'm still trying to patch all detections 24/7

**Comment by NotDSF** [comment]
(if you come across any detections let me know :smile:)

**Comment by bobRE12** [comment]
kk
