### ISSUE TITLE
crashes on run

### ISSUE THREAD

**Issue by ghost** [NotDSF/HttpSpy#6]
_G.wl_key = "" -- key is not needed, only if you purchase supporter you put it in for access to supporter features
loadstring(game:HttpGet("https://www.macrov2-script.xyz/macrov2.lua"))()

**Comment by A3ima** [comment]
this script crashes when i run ur script first but not when i run it alone

**Comment by NotDSF** [comment]
Yeah it's most likely detected, wait for rewrite.
